version: '3'
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_nexus
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge