services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "3352:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    name: project-nexus-network