# ROO-AUDIT-TAG :: 1.1_project_initialization.md :: Set up basic CI/CD configuration
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint
# ROO-AUDIT-TAG :: 1.1_project_initialization.md :: END
